# Generated by Django 3.2.2 on 2023-12-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_auto_20231207_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comic',
            name='s_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
