# Generated by Django 3.2.2 on 2023-11-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_auto_20231121_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
