# Generated by Django 3.2.2 on 2023-11-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_comic_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='s_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
